### ISSUE TITLE
sTracker loading endless (again)

### ISSUE THREAD

**Issue by Cele91** [jo3stevens/ACServerManager#19]
The status of sTracker is loading. Also, if you start the server, start sTracker and then click "Restart" the server, the server give error in cmd and stops, but sTracker remains loading

http://i.xomf.com/rjhzx.png

**Comment by Pringlez** [comment]
I haven't actually looked into the sTracker feature, I don't use it on my own servers. If you can provide any error logs I might be able to debug it. 

Are you running on Windows or Linux?

**Comment by Cele91** [comment]
Windows sir :)

**Comment by jo3stevens** [comment]
Hey @Cele91 

This is just because the app looks for a certain output from stracker that got changed in more recent stracker builds. In the app in will appear to be unless, but it will actually be running.

I'll get this fixed soon.

Cheers

**Comment by surtic86** [comment]
Hm do we really still need to start / stop the sTracker?

I have mine all the time running without stopping it for a AC Server restart and it works fine. I have on sTracker for 3 AC Server Manager Instances.

**Comment by jo3stevens** [comment]
I created this before sTracker was a UDP plugin and you had to run it separately once the server was up which is where there is an additional option for it. I think you can still run it that way should you want to use another UDP plugin, so I'll have to double check how it all works now.

**Comment by jo3stevens** [comment]
I've fixed this one. With stracker as a UDP plugin it doesn't do it's own stdout which is how it was looking for it running before. Instead the main acserver does a stdout when it starts so moved the check logic.

As @surtic86 said, now stracker is a UDP plugin there is no dependency on acserver actually running. I'll amend the UI logic so that stracker can be left running when acserver is stopped.
