### ISSUE TITLE
Web Site Problem

### ISSUE THREAD

**Issue by ClarkParker** [jo3stevens/ACServerManager#2]
Hi
First of all... good Job man! Like your work!!

But I've a problem here. After a while running the ACSERVERMANAGER the Website is not reachable any longer, probably about 1 hour is enough and the service is unreachable.
The AC Server runs in the meantime like a charm, sTracker also still running and works also in Game. As said, only the Web interface quit working and I can't find out what the problem is exactly.
Do you have an idea?
Thanks in Advance and please keep on your good work! 

Os: Windows Server 2012 r2

**Comment by jo3stevens** [comment]
Hi Clark

Apologies must have missed this. That's pretty strange because the AC Server and sTracker are running inside the node process, so if they still work I can't see why the website wouldn't.

I've been running this on my server for months, and we also run it on our league servers and I've never seen this issue. 

Are you seeing any errors when trying to access the web interface, or any errors in the logs? Or perhaps the windows logs?

Cheers
Joe

**Comment by ClarkParker** [comment]
Hi Joe
No Problem! Thanks for replying!
Ok... so I check all your suggestions and by viewing my firewall logs I saw that the port for node was shutting down all the time... so for everybody with the same problem:
I switch the open Port to a high Port and set the Port Options to "keep alive" and here we go... run's for nearly one Day now!
Joe... thanks for your time and help!!! Once again... good job... 

ps.: ...hope to see an option to select tyres in the future! ; )

**Comment by jo3stevens** [comment]
Good stuff Clark!

I've been working on adding the new settings from 1.2, I've done them all except for Tyres and Weather which I'll add shortly. I'll also be looking to add presets so you can save different configurations.

Cheers
Joe

**Comment by jo3stevens** [comment]
Hi Clark

Just an FYI that all 1.2 features have now been adding including Tyres and Weather

Cheers

**Comment by ClarkParker** [comment]
Thanks Joe!
And once again; thanks for your good work!!!
Please keep it on!

Cheers
Flo
